RENAME GESCHAEFTSPARTNER TO GPTMP;
/

CREATE TABLE GESCHAEFTSPARTNER  AS
(
SELECT  g.GESCHAEFTSPARTNERNUMMER, 
        g.STRASSE,
        g.NUMMER,
        g.PLZ,
        g.IBAN,
        g.EMAIL,
        g.TELEFON_NUMMERN        
FROM GPTMP g
);
/

ALTER TABLE GESCHAEFTSPARTNER
ADD ORT SDO_GEOMETRY;
/

ALTER TABLE GESCHAEFTSPARTNER
ADD CONSTRAINT GESCHAEFTSPARTNER_PK2 PRIMARY KEY (GESCHAEFTSPARTNERNUMMER);
/

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) 
   VALUES ('GESCHAEFTSPARTNER', 'ORT', 
      SDO_DIM_ARRAY 
        (SDO_DIM_ELEMENT('LONG', -180.0, 180.0, 0.5), 
      SDO_DIM_ELEMENT('LAT', -90.0, 90.0, 0.5)), 
      4055 );

commit;

CREATE INDEX "IDX_GESCHAEFTSPARTNER" ON "GESCHAEFTSPARTNER" ("ORT")
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
/

INSERT INTO "ABP615"."GESCHAEFTSPARTNER" (GESCHAEFTSPARTNERNUMMER, STRASSE, NUMMER, PLZ, IBAN, EMAIL, TELEFON_NUMMERN, ORT) 
values ('100','Klosterkamp1','1234','ASDIBAN','email',null,MDSYS.SDO_GEOMETRY(2001,4055 ,MDSYS.SDO_POINT_TYPE(53.58163,9.988361,NULL),NULL,NULL));

INSERT INTO "ABP615"."GESCHAEFTSPARTNER" (GESCHAEFTSPARTNERNUMMER, STRASSE, NUMMER, PLZ, IBAN, EMAIL, TELEFON_NUMMERN, ORT) 
values ('101','Hamburg-Altona',1,'1234','ASDIBAN','email',null ,MDSYS.SDO_POINT_TYPE(53.552262,9.934844,NULL),NULL,NULL));

INSERT INTO "ABP615"."GESCHAEFTSPARTNER" (GESCHAEFTSPARTNERNUMMER, STRASSE, NUMMER, PLZ, IBAN, EMAIL, TELEFON_NUMMERN, ORT) 
values ('102','HAW',1,'1234','ASDIBAN','email',null,MDSYS.SDO_GEOMETRY(2001,4055 ,MDSYS.SDO_POINT_TYPE(53.556158,10.022125,NULL),NULL,NULL));

INSERT INTO "ABP615"."GESCHAEFTSPARTNER" (GESCHAEFTSPARTNERNUMMER, STRASSE, NUMMER, PLZ, IBAN, EMAIL, TELEFON_NUMMERN, ORT) 
values ('103','RATHAUS',1,'1234','ASDIBAN','email',null,MDSYS.SDO_GEOMETRY(2001,4055 ,MDSYS.SDO_POINT_TYPE(53.550383,9.992385,NULL),NULL,NULL));

INSERT INTO "ABP615"."GESCHAEFTSPARTNER" (GESCHAEFTSPARTNERNUMMER, STRASSE, NUMMER, PLZ, IBAN, EMAIL, TELEFON_NUMMERN, ORT) 
values ('104','RENNBAHN',1,'1234','ASDIBAN','email',null,MDSYS.SDO_GEOMETRY(2001,4055 ,MDSYS.SDO_POINT_TYPE(53.553831,10.083741,NULL),NULL,NULL));

commit;

