CREATE OR REPLACE PROCEDURE INSERT_KUNDE
(
vorname    IN VARCHAR2,
nachname   IN VARCHAR2,
strasse    IN VARCHAR2,
nummer     IN VARCHAR2,
ort        IN SDO_GEOMETRY,
plz        IN NUMBER,
iban       IN VARCHAR2,
email      IN VARCHAR2,
telefon    IN TELEFON_NUMMERN
)
AS
BEGIN
  -- CREATE GESCHAEFTSPARTNER --
  INSERT INTO GESCHAEFTSPARTNER (STRASSE, NUMMER, PLZ, IBAN, EMAIL,TELEFON_NUMMERN,ORT) 
  VALUES (strasse, nummer, plz, iban, email,telefon,ort);
  
  -- CREATE KUNDE --
  INSERT INTO KUNDE (GESCHAEFTSPARTNERNUMMER, VORNAME, NACHNAME)
  VALUES (GESCHAEFTSPARTNER_SEQ.CURRVAL, vorname, nachname);
  commit;

END INSERT_KUNDE;