CREATE OR REPLACE PROCEDURE INSERT_LIEFERANT
(
lieferantenname IN VARCHAR2,
strasse         IN VARCHAR2,
nummer          IN VARCHAR2,
ort             IN SDO_GEOMETRY,
plz             IN NUMBER,
iban            IN VARCHAR2,
email           IN VARCHAR2,
tel             IN TELEFON_NUMMERN
)
AS
BEGIN
  -- CREATE GESCHAEFTSPARTNER --
  INSERT INTO GESCHAEFTSPARTNER (STRASSE, NUMMER, PLZ, IBAN, EMAIL,ORT,TELEFON_NUMMERN) 
  VALUES (strasse, nummer, plz, iban, email,ort,tel);

  -- CREATE LIEFERANT --
  INSERT INTO LIEFERANT (GESCHAEFTSPARTNERNUMMER, LIEFERANTENNAME)
  VALUES (GESCHAEFTSPARTNER_SEQ.CURRVAL, lieferantenname);
  commit;
  

END INSERT_LIEFERANT;