DROP TRIGGER CHECK_LIEFERANT;
DROP TRIGGER CHECKPLZ;
DELETE FROM BESTELLPOSITION;
DELETE FROM BESTELLUNG;
-- CLEAR TABLE GP --
DELETE FROM GESCHAEFTSPARTNER;
-- CLEAR TABLE KUNDE --
DELETE FROM KUNDE;
-- CLEAR TABLE LIEFERANT --
DELETE FROM LIEFERANT;
