package de.haw.hamburg.productcomponent.accesslayer.view;


import de.haw.hamburg.productcomponent.accesslayer.model.Geschaeftspartner;
import de.haw.hamburg.productcomponent.accesslayer.model.Kunde;
import de.haw.hamburg.productcomponent.accesslayer.model.Lieferant;

/**
 *
 * @author dima
 */
public class GeschaeftspartnerDialog extends javax.swing.JDialog {
    
    private final String CLOSE_ACTION_COMMAND   = "CLOSE";
    private final String UPDATE_ACTION_COMMAND  = "UPDATE";
    private final String CREATE_ACTION_COMMAND  = "CREATE";
    
    private Geschaeftspartner geschaeftspartner;
    
    public GeschaeftspartnerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        switchView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lieferantenPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        ibanlField = new javax.swing.JTextField();
        emaillField = new javax.swing.JTextField();
        plzlField = new javax.swing.JTextField();
        ortlField = new javax.swing.JTextField();
        nummerlField = new javax.swing.JTextField();
        strasselField = new javax.swing.JTextField();
        createLieferantButton = new javax.swing.JButton();
        switchToKundeButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        kundenPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ibankField = new javax.swing.JTextField();
        emailkField = new javax.swing.JTextField();
        plzkField = new javax.swing.JTextField();
        ortkField = new javax.swing.JTextField();
        nummerkField = new javax.swing.JTextField();
        strassekField = new javax.swing.JTextField();
        createKundeButton = new javax.swing.JButton();
        switchToLieferantButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        vornameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nachnameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lieferantenPanel.setBackground(new java.awt.Color(254, 254, 254));
        lieferantenPanel.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(244, 244, 244));

        jLabel28.setText("Strasse");

        jLabel29.setText("Nummer");

        jLabel30.setText("Ort");

        jLabel31.setText("PLZ");

        jLabel32.setText("E-Mail");

        jLabel33.setText("IBAN");

        createLieferantButton.setText("CREATE");
        createLieferantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLieferantButtonActionPerformed(evt);
            }
        });

        switchToKundeButton.setFont(new java.awt.Font("Padauk", 0, 8)); // NOI18N
        switchToKundeButton.setText("SWITCH");
        switchToKundeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToKundeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(switchToKundeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ibanlField, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(emaillField)
                    .addComponent(plzlField)
                    .addComponent(ortlField)
                    .addComponent(nummerlField)
                    .addComponent(strasselField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createLieferantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strasselField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nummerlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ortlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plzlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibanlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createLieferantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchToKundeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lieferantenPanel.add(jPanel6);
        jPanel6.setBounds(12, 142, 430, 342);

        jPanel7.setBackground(new java.awt.Color(244, 244, 244));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Lieferant"));

        jLabel11.setText("Name");

        nameField.setText("Lieferanten-Name");
        nameField.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameField))
                .addGap(0, 51, Short.MAX_VALUE))
        );

        lieferantenPanel.add(jPanel7);
        jPanel7.setBounds(12, 12, 430, 112);

        kundenPanel.setBackground(new java.awt.Color(254, 254, 254));
        kundenPanel.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(244, 244, 244));

        jLabel22.setText("Strasse");

        jLabel23.setText("Nummer");

        jLabel24.setText("Ort");

        jLabel25.setText("PLZ");

        jLabel26.setText("E-Mail");

        jLabel27.setText("IBAN");

        createKundeButton.setText("CREATE");
        createKundeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createKundeButtonActionPerformed(evt);
            }
        });

        switchToLieferantButton.setFont(new java.awt.Font("Padauk", 0, 8)); // NOI18N
        switchToLieferantButton.setText("SWITCH");
        switchToLieferantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToLieferantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(switchToLieferantButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ibankField, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(emailkField)
                    .addComponent(plzkField)
                    .addComponent(ortkField)
                    .addComponent(nummerkField)
                    .addComponent(strassekField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createKundeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strassekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nummerkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ortkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plzkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibankField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createKundeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchToLieferantButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kundenPanel.add(jPanel4);
        jPanel4.setBounds(12, 142, 430, 342);

        jPanel5.setBackground(new java.awt.Color(244, 244, 244));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Kunde"));

        jLabel10.setText("Vorname");

        vornameField.setText("Max");
        vornameField.setFocusCycleRoot(true);

        jLabel1.setText("Nachname");

        nachnameField.setText("Musterman");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vornameField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(nachnameField))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vornameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nachnameField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        kundenPanel.add(jPanel5);
        jPanel5.setBounds(12, 12, 430, 112);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kundenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lieferantenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kundenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lieferantenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(lieferantenPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(kundenPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void viewDialog(Geschaeftspartner g){
        
        setTitle("VIEW");
        if(g instanceof Kunde){
            prefillKundeFields((Kunde) g);
            switchToLieferantButton.setVisible(false);
            
            vornameField.setEditable(false);
            nachnameField.setEditable(false);
            strassekField.setEditable(false);
            nummerkField.setEditable(false);
            ortkField.setEditable(false);
            plzkField.setEditable(false);
            ibankField.setEditable(false);
            emailkField.setEditable(false);
            
            createKundeButton.setText("CLOSE");
            createKundeButton.setActionCommand(CLOSE_ACTION_COMMAND);
            showKundeView();
            
        }else{
            prefillLieferantFields((Lieferant) g);
            switchToKundeButton.setVisible(false);
            
            strasselField.setEditable(false);
            nummerlField.setEditable(false);
            ortlField.setEditable(false);
            plzlField.setEditable(false);
            ibanlField.setEditable(false);
            emaillField.setEditable(false);
            nameField.setEditable(false);
            
            createLieferantButton.setText("CLOSE");
            createLieferantButton.setActionCommand(CLOSE_ACTION_COMMAND);
            showLiereantView();
        }
        this.setVisible(true);
    }
    
    public Geschaeftspartner update(Geschaeftspartner g){
//        this.geschaeftspartner = g;
        setTitle(UPDATE_ACTION_COMMAND);
        if(g instanceof Kunde){
            prefillKundeFields((Kunde) g);
            switchToLieferantButton.setVisible(false);
            createKundeButton.setText(UPDATE_ACTION_COMMAND);
            createKundeButton.setActionCommand(UPDATE_ACTION_COMMAND);
            showKundeView();
            
        }else{
            prefillLieferantFields((Lieferant) g);
            switchToKundeButton.setVisible(false);
            createLieferantButton.setText(UPDATE_ACTION_COMMAND);
            createLieferantButton.setActionCommand(UPDATE_ACTION_COMMAND);
            showLiereantView();
        }
        
        this.setVisible(true);
        
        if(geschaeftspartner == null) return null;
        
        geschaeftspartner.setGeschaeftspartnerNummer(g.getGeschaeftspartnerNummer());
        return geschaeftspartner;
    }
    
    public Geschaeftspartner createDialog(){
        setTitle(CREATE_ACTION_COMMAND);
        this.setVisible(true);
        return geschaeftspartner;
    }
    
    private void prefillKundeFields(Kunde g){
        strassekField.setText(g.getStrasse());
        nummerkField.setText(g.getNummer());
        ortkField.setText(g.getOrt());
        plzkField.setText(Integer.toString(g.getPlz()));
        ibankField.setText(g.getIBAN());
        emailkField.setText(g.getEmail());
        vornameField.setText(g.getVorname());
        nachnameField.setText(g.getNachname());
    }
    
    private void prefillLieferantFields(Lieferant g){
        strasselField.setText(g.getStrasse());
        nummerlField.setText(g.getNummer());
        ortlField.setText(g.getOrt());
        plzlField.setText(Integer.toString(g.getPlz()));
        ibanlField.setText(g.getIBAN());
        emaillField.setText(g.getEmail());
        nameField.setText(g.getLieferantenname());
    }
    
    private void showKundeView(){
        kundenPanel.setVisible(true);
        lieferantenPanel.setVisible(false);
    }
    
    private void showLiereantView(){
        kundenPanel.setVisible(false);
        lieferantenPanel.setVisible(true);
    }
    
    private void switchView(){
        boolean isVisible = kundenPanel.isVisible();
        kundenPanel.setVisible(!isVisible);
        lieferantenPanel.setVisible(isVisible);
        
        if(kundenPanel.isVisible()){
            strassekField.setText(strasselField.getText());
            nummerkField.setText(nummerlField.getText());
            ortkField.setText(ortlField.getText());
            plzkField.setText(plzlField.getText());
            ibankField.setText(ibanlField.getText());
            emailkField.setText(emaillField.getText());
                    
        }else{
            strasselField.setText(strassekField.getText());
            nummerlField.setText(nummerkField.getText());
            ortlField.setText(ortkField.getText());
            plzlField.setText(plzkField.getText());
            ibanlField.setText(ibankField.getText());
            emaillField.setText(emailkField.getText());
        }
    }
    
    private void switchToLieferantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToLieferantButtonActionPerformed
        switchView();
    }//GEN-LAST:event_switchToLieferantButtonActionPerformed

    private void switchToKundeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToKundeButtonActionPerformed
        switchView();
    }//GEN-LAST:event_switchToKundeButtonActionPerformed

    private void createKundeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createKundeButtonActionPerformed
        
        switch(evt.getActionCommand()){
            case CLOSE_ACTION_COMMAND:
                this.dispose();
                break;
            default:
                String strasse  = strassekField.getText();
                String nummer   = nummerkField.getText();
                String ort      = ortkField.getText();
                int plz         = 0;
                String iban     = ibankField.getText();
                String email    = emailkField.getText();
                String vorname  = vornameField.getText();
                String nachname = nachnameField.getText();

                try{
                    plz = Integer.parseInt(plzkField.getText());
                }catch(NumberFormatException ex){}

                geschaeftspartner = new Kunde(null, strasse,nummer,ort, plz,iban,email,vorname,nachname);
                this.dispose();
        }
    }//GEN-LAST:event_createKundeButtonActionPerformed

    private void createLieferantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLieferantButtonActionPerformed
        
        switch(evt.getActionCommand()){
            case CLOSE_ACTION_COMMAND:
                this.dispose();
                break;
            default:
                
                String strasse  = strasselField.getText();
                String nummer   = nummerlField.getText();
                String ort      = ortlField.getText();
                int plz         = 0;
                String iban     = ibanlField.getText();
                String email    = emailkField.getText();
                String name     = nameField.getText();

                try{
                    plz = Integer.parseInt(plzlField.getText());
                }catch(NumberFormatException ex){}

                geschaeftspartner = new Lieferant(null, strasse, nummer, ort, plz, iban, email, name);
                this.dispose();
        
        }
    }//GEN-LAST:event_createLieferantButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createKundeButton;
    private javax.swing.JButton createLieferantButton;
    private javax.swing.JTextField emailkField;
    private javax.swing.JTextField emaillField;
    private javax.swing.JTextField ibankField;
    private javax.swing.JTextField ibanlField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel kundenPanel;
    private javax.swing.JPanel lieferantenPanel;
    private javax.swing.JTextField nachnameField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nummerkField;
    private javax.swing.JTextField nummerlField;
    private javax.swing.JTextField ortkField;
    private javax.swing.JTextField ortlField;
    private javax.swing.JTextField plzkField;
    private javax.swing.JTextField plzlField;
    private javax.swing.JTextField strassekField;
    private javax.swing.JTextField strasselField;
    private javax.swing.JButton switchToKundeButton;
    private javax.swing.JButton switchToLieferantButton;
    private javax.swing.JTextField vornameField;
    // End of variables declaration//GEN-END:variables
}
