CREATE OR REPLACE TRIGGER CHECK_LIEFERANT 
BEFORE INSERT ON LIFERANT 
FOR EACH ROW

DECLARE
  ANZAHL    NUMBER;

BEGIN
IF :NEW.ANSCHRIFT IS NOT NULL THEN
    SELECT COUNT(*) INTO ANZAHL
    FROM LIFERANT l
    WHERE l.ANSCHRIFT = :NEW.ANSCHRIFT;
    
    IF ANZAHL > 0 THEN RAISE RAISE_APPLICATION_ERROR(-20001,'Lieferant mit der Anschrift bereits vorhanden');
    
END;
