create or replace TRIGGER checkplz
BEFORE INSERT ON KUNDE
FOR EACH ROW

DECLARE
  ist_null      EXCEPTION;
  ist_ungueltig EXCEPTION;
  ANZAHL_PLZ    NUMBER;
  ANZAHL_STADT  NUMBER;
BEGIN
  
  IF :NEW.PLZ IS NOT NULL AND :NEW.STADT IS NOT NULL THEN
  
    SELECT COUNT(*) INTO ANZAHL_PLZ   FROM GERKEN.PLZVERZEICHNIS v WHERE v.PLZ = :NEW.PLZ;
    SELECT COUNT(*) INTO ANZAHL_STADT FROM GERKEN.PLZVERZEICHNIS v WHERE v.ORT = :NEW.STADT;
  
    IF ( ANZAHL_PLZ = 0 AND ANZAHL_STADT = 0) THEN raise ist_ungueltig;
    END IF;
  ELSE
    raise ist_null;
  END IF;  
  
  
  
EXCEPTION
  
  WHEN ist_null      THEN SYS.DBMS_OUTPUT.PUT_LINE('NOT NULL PLEASE');
  WHEN ist_ungueltig THEN SYS.DBMS_OUTPUT.PUT_LINE('NOT VALID PLZ OR CITY-NAME');
  
END;