CREATE VIEW GP_VIEW AS
SELECT    LF.GESCHAEFTSPARTNERNUMMER GESCHAEFTSPARTNERNUMMER,
          LF.LIEFERANTENNAME LIEFERANTENNAME,
          GP.STRASSE STRASSE,
          GP.NUMMER NUMMER,
          GP.PLZ PLZ,
          GP.IBAN IBAN,
          GP.EMAIL EMAIL
FROM      LIEFERANT LF,
          GESCHAEFTSPARTNER GP
WHERE     LF.GESCHAEFTSPARTNERNUMMER = GP.GESCHAEFTSPARTNERNUMMER;