CREATE OR REPLACE PROCEDURE INSERT_KUNDE
(
vorname    IN VARCHAR2,
nachname   IN VARCHAR2,
strasse    IN VARCHAR2,
nummer     IN VARCHAR2,
ort        IN VARCHAR2,
plz        IN NUMBER,
iban       IN VARCHAR2,
email      IN VARCHAR2
)
AS
BEGIN
  -- CREATE GESCHAEFTSPARTNER --
  INSERT INTO GESCHAEFTSPARTNER (STRASSE, NUMMER, ORT, PLZ, IBAN, EMAIL) 
  VALUES (strasse, nummer, ort, plz, iban, email);
  
  -- CREATE KUNDE --
  INSERT INTO KUNDE (GESCHAEFTSPARTNERNUMMER, VORNAME, NACHNAME)
  VALUES (GESCHAEFTSPARTNER_SEQ.CURRVAL, vorname, nachname);
  commit;

END INSERT_KUNDE;