create or replace PROCEDURE CREATE_GESCHAEFTSPARTNER 
(
STRASSE   IN VARCHAR2,
NUMMER    IN VARCHAR2,
ORT       IN VARCHAR2,
PLZ       IN NUMBER,
IBAN      IN VARCHAR2,
EMAIL     IN VARCHAR2,
GESCHNAME IN VARCHAR2,
NACHNAME  IN VARCHAR2
) AS

BEGIN
    -- finde Die Sequenz mit der Letzten nummer heraus
    if (NACHNAME is null) then
      INSERT INTO GESCHAEFTSPARTNER(STRASSE, NUMMER, ORT, PLZ, IBAN, EMAIL) 
      VALUES (STRASSE, NUMMER, ORT, PLZ, IBAN, EMAIL);
      INSERT () INTO GESCHAEFTSPARTNER;
    else
    end if;
    
END CREATE_GESCHAEFTSPARTNER;