CREATE OR REPLACE PROCEDURE GETFULLPRICEFROMGP(BPREIS OUT FLOAT) AS 
BEGIN
IF BESTELLUNG.PREIS THEN
  SELECT    SUM(BS.PREIS) INTO BPREIS
  FROM      GESCHAEFTSPARTNER GP,
            BESTELLUNG BS
  WHERE     GP.GESCHAEFTSPARTNERNUMMER = BS.KUNDENNUMMER;
ELSE
  BPREIS := 0;
END IF;
  DBMS_OUTPUT.put_line(BPREIS);
END GETFULLPRICEFROMGP;