@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/1 - Aufgabe/Aufgabe1.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/1 - Aufgabe/Testdaten.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/2 - Aufgabe/INSERT-Artikel.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/2 - Aufgabe/INSERT-unterartikel.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/1 - Aufgabe/Bestellung.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/DATENMIGRATION.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/2 - Aufgabe/CREATE_PRODUKTIONSAUFTRAG.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/2 - Aufgabe/CREATE_TRIGGER-checkPLZ.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_FUNCTION-decreaseArtMenge.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_FUNCTION-decreaseUnterArtMenge.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_FUNCTION-getArtMenge.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_FUNCTION_getUnterartikel.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_PROCEDURE-RECURSIVESQL.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_TRIGGER-check_bestellposition.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/3 - Aufgabe/CREATE_TRIGGER-check_lieferant.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/4 - Aufgabe/CREATE-VIEW.sql'
@'/home/dima/Studium/7_Semester_WiSe2017/Git/Datenbank-Design/0 - doc/4 - Aufgabe/GET_FULL_PRICE_FROM_GP_BESTELLUNGEN.sql'

