@'Z:\Git\Datenbank-Design\0 - doc\1 - Aufgabe\Aufgabe1.sql'
@'Z:\Git\Datenbank-Design\0 - doc\1 - Aufgabe\Testdaten.sql'
@'Z:\Git\Datenbank-Design\0 - doc\2 - Aufgabe\INSERT-Artikel.sql'
@'Z:\Git\Datenbank-Design\0 - doc\2 - Aufgabe\INSERT-unterartikel.sql'
@'Z:\Git\Datenbank-Design\0 - doc\1 - Aufgabe\Bestellung.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\DATENMIGRATION.sql'
@'Z:\Git\Datenbank-Design\0 - doc\2 - Aufgabe\CREATE_PRODUKTIONSAUFTRAG.sql'
@'Z:\Git\Datenbank-Design\0 - doc\2 - Aufgabe\CREATE_TRIGGER-checkPLZ.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_FUNCTION-decreaseArtMenge.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_FUNCTION-decreaseUnterArtMenge.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_FUNCTION-getArtMenge.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_FUNCTION_getUnterartikel.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_PROCEDURE-RECURSIVESQL.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_TRIGGER-check_bestellposition.sql'
@'Z:\Git\Datenbank-Design\0 - doc\3 - Aufgabe\CREATE_TRIGGER-check_lieferant.sql'
@'Z:\Git\Datenbank-Design\0 - doc\4 - Aufgabe\CREATE-VIEW.sql'

